import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiTailwindcss,
  SiReact,
  SiVite,
  SiNodedotjs,
  SiBootstrap,
  SiFirebase,
  SiMongodb,
  SiMongoose,
  SiPostgresql,
  SiPrisma,
  SiRedux,
  SiNextdotjs,
  SiTypescript,
  SiGit,
  SiExpress,
  SiPostman,
  SiVercel,
} from "react-icons/si";

export const techStacks = {
  frontend: [
    { IconComponent: SiJavascript, language: "JavaScript" },
    { IconComponent: SiTypescript, language: "TypeScript" },
    { IconComponent: SiReact, language: "ReactJS" },
    { IconComponent: SiNextdotjs, language: "Next.js" },
    { IconComponent: SiRedux, language: "Redux" },
    { IconComponent: SiTailwindcss, language: "Tailwind CSS" },
    { IconComponent: SiBootstrap, language: "Bootstrap" },
    { IconComponent: SiVite, language: "Vite" },
  ],
  backend: [
    { IconComponent: SiNodedotjs, language: "Node JS" },
    { IconComponent: SiExpress, language: "Express" },
    { IconComponent: SiMongodb, language: "MongoDB" },
    { IconComponent: SiPostgresql, language: "PostgreSQL" },
    { IconComponent: SiPrisma, language: "Prisma" },
    { IconComponent: SiMongoose, language: "Mongoose" },
  ],
  tools: [
    { IconComponent: SiGit, language: "Git" },
    { IconComponent: SiVercel, language: "Vercel" },
    { IconComponent: SiFirebase, language: "Firebase" },
    { IconComponent: SiPostman, language: "Postman" },
  ],
};
